// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgiEpEUunAYS6j9k3WXxTTAzSapZ8biqo',
    appId: '1:908584196503:web:bed88f48d00302c13b0cd2',
    messagingSenderId: '908584196503',
    projectId: 'assignmentpro-5eb77',
    authDomain: 'assignmentpro-5eb77.firebaseapp.com',
    storageBucket: 'assignmentpro-5eb77.appspot.com',
    measurementId: 'G-NSFEHY2HNG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2PrI-owOnyo0J4RnXZ2tuFvmtMMkTa84',
    appId: '1:908584196503:android:d72b359ff9ce6b593b0cd2',
    messagingSenderId: '908584196503',
    projectId: 'assignmentpro-5eb77',
    storageBucket: 'assignmentpro-5eb77.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTgtmjTo5WSQTEjO5zcwfkdEJ_xJLViDo',
    appId: '1:908584196503:ios:177b2e8c8bc82d303b0cd2',
    messagingSenderId: '908584196503',
    projectId: 'assignmentpro-5eb77',
    storageBucket: 'assignmentpro-5eb77.appspot.com',
    iosClientId: '908584196503-nltasf8fmieo1cecfagtea1v0bglcmqb.apps.googleusercontent.com',
    iosBundleId: 'com.example.assignmentpro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTgtmjTo5WSQTEjO5zcwfkdEJ_xJLViDo',
    appId: '1:908584196503:ios:7a67ca74eac1bd173b0cd2',
    messagingSenderId: '908584196503',
    projectId: 'assignmentpro-5eb77',
    storageBucket: 'assignmentpro-5eb77.appspot.com',
    iosClientId: '908584196503-dmfu454usdqak88sdho71hiekpjea248.apps.googleusercontent.com',
    iosBundleId: 'com.example.assignmentpro.RunnerTests',
  );
}
